### ISSUE TITLE
Test Failures for Plone3.3.5

### ISSUE THREAD

**Issue by WouterVH** [collective/Products.EasyNewsletter#5]
After running thebuildout for  test-plone-3.3.x.cfg

```python
wouter@midgard: /opt/zope/Products.EasyNewsletter > bin/test 
Running Products.EasyNewsletter.testing.EasyNewsletter:Integration tests:
  Set up plone.testing.zca.LayerCleanup in 0.271 seconds.
  Set up plone.testing.z2.Startup in 0.204 seconds.
  Set up plone.app.testing.layers.PloneFixture/opt/zope/Products.EasyNewsletter/parts/zope2/lib/python/zope/configuration/xmlconfig.py:323: DeprecationWarning: zope.app.annotation has moved to zope.annotation. Import of zope.app.annotation will become unsupported in Zope 3.5
  __import__(arguments[0])
/opt/zope/Products.EasyNewsletter/eggs/Products.CMFCore-2.1.2-py2.4.egg/Products/CMFCore/DirectoryView.py:497: UserWarning: DirectoryView gruf refers to a non-existing path 'Products.GroupUserFolder:skins/gruf'
  (self.id, reg_key), UserWarning)
/opt/zope/Products.EasyNewsletter/eggs/Products.CMFCore-2.1.2-py2.4.egg/Products/CMFCore/DirectoryView.py:497: UserWarning: DirectoryView gruf_plone_2_0 refers to a non-existing path 'Products.GroupUserFolder:skins/gruf_plone_2_0'
  (self.id, reg_key), UserWarning)
/opt/zope/Products.EasyNewsletter/eggs/Products.PlonePAS-3.12-py2.4.egg/Products/PlonePAS/setuphandlers.py:39: DeprecationWarning: portal_groups.getGroupIds is deprecated and will be removed in Plone 4.0. Use PAS searchGroups instead
  existing = gtool.listGroupIds()
 in 5.986 seconds.
  Set up Products.EasyNewsletter.testing.EasyNewsletter in 0.525 seconds.
  Set up Products.EasyNewsletter.testing.EasyNewsletter:Integration in 0.000 seconds.
  Running:
    1/7 (14.3%)/opt/zope/Products.EasyNewsletter/parts/zope2/lib/python/OFS/subscribers.py:73: DeprecationWarning: Products.EasyNewsletter.content.ENLTemplate.ENLTemplate.manage_afterAdd is discouraged. You should use event subscribers instead.
  DeprecationWarning)
                
  Ran 7 tests with 0 failures and 0 errors in 0.668 seconds.
Tearing down left over layers:
  Tear down Products.EasyNewsletter.testing.EasyNewsletter:Integration in 0.000 seconds.
  Tear down Products.EasyNewsletter.testing.EasyNewsletter in 0.006 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.083 seconds.
  Tear down plone.testing.z2.Startup in 0.005 seconds.
  Tear down plone.testing.zca.LayerCleanup
Traceback (most recent call last):
  File "/opt/zope/Products.EasyNewsletter/bin/test", line 133, in ?
    collective.xmltestreport.runner.run((['--auto-color', '--auto-progress']) + [
  File "/opt/zope/Products.EasyNewsletter/eggs/collective.xmltestreport-1.2.4-py2.4.egg/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/opt/zope/Products.EasyNewsletter/eggs/collective.xmltestreport-1.2.4-py2.4.egg/collective/xmltestreport/runner.py", line 72, in run_internal
    runner.run()
  File "/opt/zope/Products.EasyNewsletter/eggs/zope.testrunner-4.0.4-py2.4.egg/zope/testrunner/runner.py", line 148, in run
    self.run_tests()
  File "/opt/zope/Products.EasyNewsletter/eggs/zope.testrunner-4.0.4-py2.4.egg/zope/testrunner/runner.py", line 252, in run_tests
    tear_down_unneeded(self.options, (), setup_layers, True)
  File "/opt/zope/Products.EasyNewsletter/eggs/zope.testrunner-4.0.4-py2.4.egg/zope/testrunner/runner.py", line 644, in tear_down_unneeded
    l.tearDown()
  File "/opt/zope/Products.EasyNewsletter/eggs/plone.testing-3.0a2-py2.4.egg/plone/testing/zca.py", line 276, in tearDown
    zope.testing.cleanup.cleanUp()
  File "/opt/zope/Products.EasyNewsletter/eggs/zope.testing-3.8.7-py2.4.egg/zope/testing/cleanup.py", line 64, in cleanUp
    func(*args, **kw)
  File "/opt/zope/Products.EasyNewsletter/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/zcml.py", line 292, in cleanUpProfiles
    del _profile_registry._profile_info[profile_id]
KeyError: u'Products.EasyNewsletter:default'
```

**Comment by jensens** [comment]
outdated. no longer supported on mastyer
